BUTTON_APPLY_GREEN="background-color: #2ecc71; color: #ffffff; font-weight: bold;"
BUTTON_APPLY_BLUESKY="background-color: #2eb0cc; color: white; font-weight: bold;"
BUTTON_ORANGE = "background-color: #f39c12; color: white; font-weight: bold;"
BUTTON_CANCEL="background-color: #e74c3c; color: white; font-weight: bold;"
BUTTON_DISABLE="background-color: #787878; color: #9d9d9d; font-weight: bold;"